### ISSUE TITLE
Month & Year Drop Down immediately disappear

### ISSUE THREAD

**Issue by softmastx** [fobbyal/pikaday-react#1]
I can't select months & years drop down with React 16.12.0!

**Comment by fobbyal** [comment]
This has not been touched in 4 years and 4 years is a lot of time. Please use this only for educational purposes. If your project does not require pickaday specifically, you can choose from the options below. This by far not a exhaustive list there are a lot of good date selector React components out there .  


https://ant.design/components/date-picker/

https://github.com/airbnb/react-dates
